# Get user
GET http://localhost:3333/api/users/5ebc9b18-6564-4dec-b559-10402a71ab36 HTTP/1.1

###
# Update user
POST http://localhost:3333/api/users/7aef6925-4fe5-4057-b5cc-cc7cf214df05/update HTTP/1.1
Content-Type: application/json

{
  "firstName": "Leonid",
  "lastName": "Brejnev"
}
###

# Update user passowrd
POST http://localhost:3333/api/users/7aef6925-4fe5-4057-b5cc-cc7cf214df05/update-password HTTP/1.1
Content-Type: application/json

{
  "oldPassword": "asdfghjkl",
  "newPassword": "qwertyuiop"
}
###
